Repository 6trillion/Assignment8-TeamB, pull requests merged in 2021-08, with the labels that each got.

#2 Chore: CRA 초기 세팅 #1
  .eslintrc.json
  .gitignore
  .prettierrc
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.tsx
  src/index.tsx
  src/react-app-env.d.ts
  tsconfig.json
  yarn.lock
Labels: chore

#8 Feat/local storage
  .eslintrc.json
  src/App.tsx
  src/components/index.tsx
  src/constants/index.tsx
  src/styles/index.tsx
  src/types/index.ts
  src/utils/Tokens.ts
  src/utils/index.tsx
  src/utils/localStorage.ts
Labels: feat, refactor

#11 Feat/body
  package-lock.json
  src/App.tsx
  src/components/body/PlusButton.tsx
  src/components/body/TodoBoard.tsx
  src/components/body/TodoBody.tsx
  src/components/body/TodoInput.tsx
  src/components/body/TodoItem.tsx
  src/components/body/TodoSideTab.tsx
  src/components/header/Header.tsx
  src/components/header/Space.tsx
  src/components/index.tsx
  src/constants/index.tsx
  src/styles/index.tsx
  src/styles/reset.css
  src/types/index.ts
  yarn.lock
Labels: feat

#13 생성일 기준 필터링 구현
  package.json
  src/App.tsx
  src/assets/icon/close.svg
  src/assets/icon/filter.svg
  src/components/Filter.tsx
  src/components/body/TodoBody.tsx
  src/components/body/TodoItem.tsx
  src/components/body/TodoItemDetail.tsx
  src/components/body/TodoSideTab.tsx
  src/components/header/Header.tsx
  src/constants/index.tsx
  src/index.tsx
  src/types/index.ts
  yarn.lock
Labels: feat

#14 Feat: 중요도 기준 필터링 기능
  src/App.tsx
  src/components/Filter.tsx
  src/components/body/TodoBody.tsx
  src/components/header/Header.tsx
  src/types/index.ts
Labels: feat, design
